# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: assessor.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'assessor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61ssessor.proto\x12\x08\x61ssessor\"x\n\x0f\x41ssessorRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x16\n\x0esource_machine\x18\x02 \x01(\t\x12\x18\n\x10source_worker_id\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\x12\x0e\n\x06gpu_id\x18\x05 \x01(\x05\"]\n\x10\x41ssessorResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\x0c\x12\x15\n\rerror_message\x18\x04 \x01(\t2_\n\x0f\x41ssessorService\x12L\n\x11ProcessAssessment\x12\x19.assessor.AssessorRequest\x1a\x1a.assessor.AssessorResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'assessor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASSESSORREQUEST']._serialized_start=28
  _globals['_ASSESSORREQUEST']._serialized_end=148
  _globals['_ASSESSORRESPONSE']._serialized_start=150
  _globals['_ASSESSORRESPONSE']._serialized_end=243
  _globals['_ASSESSORSERVICE']._serialized_start=245
  _globals['_ASSESSORSERVICE']._serialized_end=340
# @@protoc_insertion_point(module_scope)
