# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import assessor_pb2 as assessor__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in assessor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AssessorServiceStub(object):
    """The Assessor service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessAssessment = channel.unary_unary(
                '/assessor.AssessorService/ProcessAssessment',
                request_serializer=assessor__pb2.AssessorRequest.SerializeToString,
                response_deserializer=assessor__pb2.AssessorResponse.FromString,
                _registered_method=True)


class AssessorServiceServicer(object):
    """The Assessor service definition
    """

    def ProcessAssessment(self, request, context):
        """Processes an assessment request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssessorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessAssessment': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessAssessment,
                    request_deserializer=assessor__pb2.AssessorRequest.FromString,
                    response_serializer=assessor__pb2.AssessorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'assessor.AssessorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('assessor.AssessorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AssessorService(object):
    """The Assessor service definition
    """

    @staticmethod
    def ProcessAssessment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assessor.AssessorService/ProcessAssessment',
            assessor__pb2.AssessorRequest.SerializeToString,
            assessor__pb2.AssessorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
